steps:
# 1. Build the Docker image
# This step runs 'docker build' using our Dockerfile.
# The image will be tagged and ready for the next step.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest', '.']

# 2. Push the image to Artifact Registry
# This pushes the image we just built to Google's container registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest']

# 3. Deploy to Cloud Run
# This step takes the newly pushed image and deploys it as a new revision
# to our Cloud Run service.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'
  - '--region=${_REGION}'
  - '--platform=managed'
  - '--allow-unauthenticated'

# Define the image name for logging purposes
images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'